# Generated by Django 3.0.4 on 2020-04-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
