# Generated by Django 3.0.4 on 2020-04-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharings', '0002_sharing_is_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='is_secret',
            field=models.BooleanField(default=True),
        ),
    ]
