# Generated by Django 3.0.4 on 2020-04-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharings', '0003_auto_20200424_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='is_secret',
            field=models.NullBooleanField(),
        ),
    ]
