# Generated by Django 3.0.4 on 2020-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=20, verbose_name='강아지 타입')),
                ('description', models.TextField(verbose_name='테스트 결과 설명')),
            ],
        ),
    ]
