# Generated by Django 3.0.4 on 2020-05-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0002_auto_20200504_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogs',
            old_name='shynewss',
            new_name='shyness',
        ),
    ]
