# Generated by Django 3.0.4 on 2020-05-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0003_auto_20200504_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.IntegerField(null=True, verbose_name='자신감')),
                ('shyness', models.IntegerField(null=True, verbose_name='부끄러움')),
                ('independence', models.IntegerField(null=True, verbose_name='자립심')),
                ('positive', models.IntegerField(null=True, verbose_name='긍정 마인드')),
                ('adaptability', models.IntegerField(null=True, verbose_name='적응력')),
                ('doggy', models.CharField(max_length=20, verbose_name='강아지')),
            ],
        ),
    ]
