# Generated by Django 3.0.4 on 2020-05-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0004_userstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='텍스트')),
                ('score', models.IntegerField(verbose_name='배점')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20, verbose_name='질문')),
                ('personality', models.CharField(choices=[(1, 'Confidence'), (2, 'Shyness'), (3, 'Independence'), (4, 'Positiviveness'), (5, 'Adaptability')], max_length=30, verbose_name='성격')),
            ],
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='types',
            new_name='breed',
        ),
        migrations.RenameField(
            model_name='dogs',
            old_name='positive',
            new_name='positiveness',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doggy.Question', verbose_name='질문'),
        ),
    ]
