# Generated by Django 3.0.4 on 2020-05-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0005_auto_20200504_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='image',
            field=models.URLField(default='', verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='question',
            name='personality',
            field=models.CharField(choices=[(1, 'Confidence'), (2, 'Shyness'), (3, 'Independence'), (4, 'Positiveness'), (5, 'Adaptability')], max_length=30, verbose_name='성격'),
        ),
    ]
