# Generated by Django 3.0.4 on 2020-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggy', '0006_auto_20200505_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='breed_kr',
            field=models.CharField(default='', max_length=20, verbose_name='견종'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='견종'),
        ),
    ]
